### ISSUE TITLE
后缀自动机页面的侧边栏弹不出来了 

### ISSUE THREAD

**Issue by Enter-tainer** [OI-wiki/feedback-sys#80]
https://oi-wiki.org/string/sam/
```
Uncaught TypeError: Cannot read properties of null (reading 'querySelectorAll')
    at j (oiwiki-feedback-sys-frontend.js?v=922d387ae4af50f43ae015255d9ba9c5:5:67)
    at Module.lt [as setupReview] (oiwiki-feedback-sys-frontend.js?v=922d387ae4af50f43ae015255d9ba9c5:64:6432)
    at Object.next (oiwiki-feedback-sys-frontend.js?v=132aa38e6c80c1de197bc533798b8c61:43:33)
    at e.next (Subscriber.ts:161:25)
    at t._next (Subscriber.ts:119:22)
    at t.next (Subscriber.ts:75:12)
    at Subject.ts:68:20
    at ct (errorContext.ts:29:5)
    at t.next (Subject.ts:61:5)
    at t.next (ReplaySubject.ts:65:15)

```

<img width="555" alt="image" src="https://github.com/user-attachments/assets/778e401d-4299-46e9-aba1-c2f45700d2af">

**Comment by Enter-tainer** [comment]
好像准确来说是所有的都弹不出来了

**Comment by shaokeyibb** [comment]
> 好像准确来说是所有的都弹不出来了

草？
